version: "1.0"
info:
  model: int-scaffold
packages:
- name: KmatoriginsalesforceProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KmatoriginsalesforceProject
  gitUsername: karthikbm
  gitBranch: main
- name: Lakshmi
  version: "1.0"
  gitServerName: lakrgit
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: lakshmidevi277
  gitBranch: main
services:
- serviceName: project.kmatoriginsalesforce.integrations:KMAT_SYED
  packages:
  - name: KmatoriginsalesforceProject
    version: "1.0"
  - name: Lakshmi
    version: "1.0"
- serviceName: ccs:sf_query
  packages:
  - name: Lakshmi
    version: "1.0"
